name = "PAMAuth"
uuid = "65a6d51f-e0d2-4d04-b1c7-956c784c774e"
authors = ["Connor Burns <cburns@cot.llc>"]
version = "0.1.0"

[compat]
julia = "1.5"

[deps]
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
